package de.unibi.cebitec.bibiworkflow.app;

import de.unibi.cebitec.bibiworkflow.bs2.Bs2Document;
import de.unibi.cebitec.bibiworkflow.bs2.IBs2Document;
import de.unibi.techfak.bibiserv.cms.Tfunction;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.JAXBException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    
    
    private static String path = "/home/pol3waf/Programming/Projects/basedoc/BasespaceConverter/SampleFiles/blast_final_2.bs2";
    
    
    
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        try {
            IBs2Document bs2document = new Bs2Document(path);
            Tfunction function = bs2document.getFunctions().get(0);
            bs2document.getCommandLineOrder(function);
        } catch (JAXBException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
