input_otu_table:
    class: File
    path: /home/pol3waf/Programming/Projects/MasterProject/bibi-workflow/testsuite/myRuns/otu_table_mc2_w_tax_no_pynast_failures_w_metadata.biom

input_mapping:
    class: File
    path: /home/pol3waf/Programming/Projects/MasterProject/bibi-workflow/testsuite/myRuns/otu_table_mc2_w_tax_no_pynast_failures_w_metadata.biom

input_tree_file:
    class: File
    path: /home/pol3waf/Programming/Projects/MasterProject/bibi-workflow/testsuite/myRuns/rep_set.tre

input_parameter_file:
    class: File
    path: /home/pol3waf/Programming/Projects/MasterProject/bibi-workflow/testsuite/myRuns/

parallel: false

jobs_to_start: 1
  
    
    
