input_merged_reads:
    class: File
    path: /home/pol3waf/Programming/Projects/MasterProject/SampleData/outputs/flash/out.extendedFrags.fastq

input_metadata_mapping_files:
    class: File
    path: /home/pol3waf/Programming/Projects/MasterProject/SampleData/outputs/combinedMapping/combined_mapping.txt
    
phred_quality_threshold: 19

phred_offset: 33

sample_id: frag

barcode_type: 'not-barcoded'

output_demultiplexed_directory_outputFileName: .
