input_otu_table:
    class: File
    path: /home/pol3waf/Programming/Projects/MasterProject/bibi-workflow/testsuite/testrun/otu_table_mc2_w_tax_no_pynast_failures.biom

input_mapping:
  class: File
  path: /home/pol3waf/Programming/Projects/MasterProject/bibi-workflow/testsuite/predefined_files/combined_mapping.txt.valid

#input_tree_file:
#    class: File
#    path: /home/pol3waf/Programming/Projects/MasterProject/bibi-workflow/testsuite/testrun/rep_set.tre

#input_parameter_file:
#  class: File
#  path: /home/pol3waf/Programming/Projects/MasterProject/bibi-workflow/testsuite/predefined_files/alpha_parameters_TOUSE.txt


#jobs_to_start: 1

#parallel: false

PLACEHOLDER_output_taxa_plots_outputFileName: taxa_plots_out_stdout.txt

