/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import de.unibi.cebitec.bibiworkflow.app.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    
}
